Test
zalando/expan pull request #86
Opened 2017-03-13 17:28 UTC by s4826

- Remove duplicated code in ```fixed_horizon_delta()```
- updated tests to reflect new method signature for ```fixed_horizon_delta()```

2017-03-14 08:50 UTC, jbao approved these changes

2017-03-14 09:46 UTC, mkolarek commented
:+1:

2017-03-14 09:46 UTC, mkolarek approved these changes

2017-03-14 10:28 UTC, gbordyugov requested changes
Hi,

great job! I'm however still a bit unconvinced about your solution to move the duplicate code into the `mock` function. Does it eliminate the duplicate code in both `delta()` and `fixed_horizon_delta()`?

Plus introducing a `res` argument to `fixed_horizon_delta()` makes its handling a bit special in comparison to other workers.

Best,
gb

2017-03-14 10:28 UTC, gbordyugov commented on expan/core/experiment.py
> +	def fixed_horizon_delta(self,
Is introducing an additional parameter to fixed_horizon_delta() worth it? It seems to me that this introduces an inhomogeneity across the fourth `delta` workers

2017-03-14 10:28 UTC, gbordyugov commented on tests/tests_core/test_results.py
> +	Create a results object for any tests involving fixed_horizon_delta()
why factor out this functionality as a separate function? is it going to be used anywhere besides `fixed_horizon_delta()`?

addendum: would this code persist in Experiment.delta() further?

2017-03-15 08:34 UTC, gbordyugov approved these changes
Hi,

I totally misunderstood the logic of what you did, now, after a bit of pondering, it looks great to me.

2017-03-15 08:52 UTC, jbao commented
This resolves #81 .

2017-03-15 08:52 UTC, merged